### PR TITLE
Fix duplicate removal

### PR DESCRIPTION
**Pull request by Toby222**
fix(dupes): fix duplicate file matching
chore: remove constant newline printing in file matching

### CODE REVIEW

**Comment by CyanVoxel** [comment]
Looks like this was missed in the #156 pathlib refactor and has been hanging around ever since. Come to think of it I probably haven't used the duplicate removal since before that PR! Normally I would request opening an issue to explain what was fixed, but it seems pretty self explanatory here. Good catch! 👍

**Comment by Toby222** [comment]
I couldn't think of an issue that wouldn't have had more words than the code in the PR to fix it :^)
I'm moving away from Google Photos and had to turn the album folders into tags, which this just happened to be perfect for

**Review by eivl — APPROVED** [review]
Kaizen commit approval.

**Comment by CyanVoxel** [comment]
@Toby222 Why the closure and wipe? 🤔

**Comment by Toby222** [comment]
Ooooppps, I forgot that GitHub does that

**Comment by Toby222** [comment]
(had to rebase onto main to make GitHub let me reopen the issue ^^)

**Comment by CyanVoxel** [comment]
Alright, I'll try rebasing this back to `Alpha-v9.4` - it *should* be fine, but there's some weird git shenanigans going on...

**Comment by CyanVoxel** [comment]
Ahhh now all the newer flake changes from `main` are in here too... I might just have to update `Alpha-v9.4` from main before merging this

**Comment by Toby222** [comment]
git shenanigans ^^;
Yea my bad but it works:tm:

**Pull request merged**
