### PR TITLE
fix: stop sqlite db from being updated while running tests

### LINKED ISSUE #644: [Bug]: Pytest modifies and updates search_library sqlite file
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha v9.5.0 (main branch)

### Operating System & Version

Windows 10

### Description

Running Pytest (specifically one or more of the search_library tests) results in the test database being modified, resulting in git wanting to commit the changes.
The internal change seems to be a result of the [file change counter](https://www.sqlite.org/fileformat.html) value being updated.

### Expected Behavior

The test database should not be changed on disk, especially when no changes are being made to it. It should also not be included in the .gitignore because the file in question can receive genuine updates and changes.

### Steps to Reproduce

1. Clone and set up a TagStudio development environment per the [CONTRIBUTING.md](https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md) instructions
2. Run Pytest with `pytest tagstudio/tests/`
3. Observe modified file at `\TagStudio\tagstudio\tests\fixtures\search_library\.TagStudio\ts_library.sqlite`

### Logs

_No response_

### PR DESCRIPTION
**Pull request by python357-1**
This PR fixes #644 by having `make_tables` check the current autoincrement value (what the next inserted row would have as its id) on the `tags` table. Previously, an `INSERT` and a `DELETE` were always being run when a library was opened, causing the file change counter to increase

close #644 
close #646

### CODE REVIEW

**Comment by python357-1** [comment]
I don't know how to check if the schema is the same to do this - even the sqldiff tool didn't detect this. The reason we are doing the insert and delete is to make sure the next auto increment ID is at least 1000. This implementation allows it to skip updating the database if the next ID is at least 1000.

**Review by Computerdores — APPROVED** [review]
This fixes the issue for me on Win10 and I don't see anything wrong with the code either (no idea whether using `sessionmaker` is better here, but I see nothing wrong with it)

**Comment by python357-1** [comment]
yeah i actually just fixed that, realized there was no need for that to be there lol

**Review by CyanVoxel — APPROVED** [review]
Looks like this fixes the modification issues without breaking the auto-increment values 👍

**Pull request merged**
