### PR TITLE
FFmpeg Not Found Fix - Alpha v9.4

### PR DESCRIPTION
**Pull request by myxxmikeyxx**
Updated PySide6 (Qt) and Pillow and PyInstaller.
This update seems to fix the FFmpeg not found.

### CODE REVIEW

**Comment by myxxmikeyxx** [comment]
Also added quotations to the Build_MacOS_app.sh file due to directory problems if spaces exist.

**Comment by seakrueger** [comment]
Just to confirm, sorry, were you able to successfully build an .app bundle with the ffmpeg check passing? 
If I had to guess, the fix is most likely from updating PyInstaller (though I don't see any bugfix in the changelog). If possible, could you test with just updating PyInstaller? Updating Qt (Pyside) usually breaks some stuff

**Comment by myxxmikeyxx** [comment]
Same problem as before. It works when I run it from TagStudio.sh. Also it works when when running the exec file but the compiled .app does not work. Still shows that it can't find FFMPEG.

**Comment by myxxmikeyxx** [comment]
I also forgot I had to edit the Build_MacOS_app.sh so when I first tried to build it, it failed. Had to look back and grab my old one. As mentioned before I am on Intel Mac not M1 (or up) and using bash not zsh. 

Bellow is the code for the build_macos_app.sh to work (not sure if this can get added to the next release or not)
Parts that were changed: 

- `if [ ! -d $LOGS_PATH ]; then` -> `if [[ ! -d $LOGS_PATH ]]; then` 
- The if check kept failing and I found this and changed it and it works. [Link Here](https://unix.stackexchange.com/questions/306111/what-is-the-difference-between-the-bash-operators-vs-vs-vs)
- `mkdir -p $LOGS_PATH;` -> `mkdir -p "$LOGS_PATH";`
- Added Quotes because if the directory has a space in the name it fails at making it.
- `open $DIST_PATH`-> `open "$DIST_PATH"` 
- Same reason as above, if the directory has a space it fails to open.
- `printf -- "🏁 END OF TRANSMISSION"` -> `printf -- "🏁 END OF TRANSMISSION\n"`
- Just a quality of life change, otherwise the next line in terminal is attached to it
- Example: `🏁 END OF TRANSMISSION Project-Mac-Pro:TagStudio-9.4.1 myxxmikeyxx$ `
- Fixed: `🏁 END OF TRANSMISSION
Project-Mac-Pro:TagStudio-9.4.1 myxxmikeyxx$ `

`#! /usr/bin/env bash
# GETTING BASE DIR
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# SETTING UP CONSTANTS
TAGSTUDIO_NAME="TagStudio"
TAGSTUDIO_DIR="$SCRIPT_DIR/tagstudio"
TAGSTUDIO_DIR_RESOURCES="$TAGSTUDIO_DIR/resources"
TAGSTUDIO_ICON="$TAGSTUDIO_DIR/resources/icon.ico"
TAGSTUDIO_SRC="$TAGSTUDIO_DIR/src"
TAGSTUDIO_MAIN="$TAGSTUDIO_DIR/tag_studio.py"
DIST_PATH="$SCRIPT_DIR/dist"
BUILD_PATH="$SCRIPT_DIR/build"
LOGS_PATH="$BUILD_PATH/logs"

printf -- "🏁 Starting Script \n"

# CREATE VENV AND INSTALL REQUIREMENTS
printf -- "🐍 Creating Python virtual env\n"
python3 -m venv .venv 
source .venv/bin/activate

if [[ ! -d $LOGS_PATH ]]; then
  printf -- "📁 Creating Logs folder\n"
  mkdir -p "$LOGS_PATH";
fi

printf -- "💻 Installing Requirements \n"
pip install -r requirements.txt > "$LOGS_PATH/pip.log" 2>&1
pip install PyInstaller > "$LOGS_PATH/pip.log" 2>&1


if [[ "$OSTYPE" == "darwin"* ]]; then
    printf -- "🍏 MacOS Detected \n"
    SYS_CMD="--windowed"
    OS=0
fi

SECONDS=0

# CREATE COMMAND 
printf -- "⏳ Building App \n"

COMMAND=$( python -m PyInstaller \
  --name "$TAGSTUDIO_NAME" \
  --icon "$TAGSTUDIO_ICON" \
  --add-data "$TAGSTUDIO_DIR_RESOURCES:./resources" \
  --add-data "$TAGSTUDIO_SRC:./src" \
  --distpath "$DIST_PATH" \
  -p "$TAGSTUDIO_DIR" \
  --noconsole \
  --workpath "$BUILD_PATH" \
  -y "$SYS_CMD" "$TAGSTUDIO_MAIN" \
  > "$LOGS_PATH/pyinstaller.log" 2>&1 )

duration=$SECONDS

if $COMMAND; then
  printf -- "✅ Build Successfull \n"
  printf -- "⌛ $((duration)) seconds of build\n"
    if [[ "$OS" == 0 ]]; then
      printf -- "📁 Opening App folder \n"
      open "$DIST_PATH"
    fi 
else
    printf -- "❌ Error Building the app\nPlease read the logs\navailable at build/logs\n"
fi

printf -- "🏁 END OF TRANSMISSION\n"
`

**Comment by myxxmikeyxx** [comment]
Not sure what changed besides restarting the mac but the compiled version no longer can find ffmpeg either. Not sure what else I would have done but it is no longer found in the updated package compiled version.

**Comment by CyanVoxel** [comment]
So from what I understand, does the new PySide version not fix FFmpeg not being found after all?

**Comment by myxxmikeyxx** [comment]
I was not. @CyanVoxel

**Comment by CyanVoxel** [comment]
#511 has now been fixed in #629

**Pull request closed without merging**
