### PR TITLE
feat: Audio Playback

### PR DESCRIPTION
**Pull request by csponge**
This PR adds the ability to play audio files. Additionally, it adds a few new UI elements for interacting with audio. Below is a list of the newly added elements:

- Slider (used for changing the current position in the file)
- Play/Pause
- Mute/Unmute

**NOTE:** There are a few bugs to work out, but I think they would be better suited for new issues because they affect more than just the audio player.

Refs: https://github.com/TagStudioDev/TagStudio/issues/450

### CODE REVIEW

**Comment by CyanVoxel** [comment]
Any reason why this was closed?

**Comment by Nginearing** [comment]
> Any reason why this was closed?

Seems like they didn't realise deleting their fork would close the commit.

**Comment by CyanVoxel** [comment]
> Ah, that's my bad. Didn't realize that would happen.
> 
> Would it be possible to fix this by recreating the branch? If not, maybe I can open a new PR?
> 
> Sorry for the confusion.

I believe a new PR would be needed if the original fork and/or branch is deleted, unless there's a way to undo that in a way that GitHub is pleased with that I'm unaware of

**Comment by csponge** [comment]
Okay, I'll work on making a new PR.

Again, sorry for the confusion.

**Pull request closed without merging**
