### PR TITLE
Begin adding query parsing

### PR DESCRIPTION
**Pull request by python357-1**
For the moment this will be a draft PR to track the status of adding query parsing. When finished it will likely implement most or all of the features in #272, #314, and #325, with the possibility of others being implemented as well.

### CODE REVIEW

**Comment by Tishj** [comment]
This sounds like it could benefit from using a Parsing Expression Grammar (<https://peps.python.org/pep-0617/#background-on-peg-parsers>), as it looks like this PR is kind of implementing a parser/tokenizer.

This could be made much simpler by using an existing library and only defining a grammar based on the wants and needs outlined by the referenced issues

**Comment by Tishj** [comment]
A basic example using `parsimonious` (not sure this is the best but it's one of the options)

```py
from parsimonious.grammar import Grammar

GRAMMAR = r"""
expr        = (entry / emptyline)*
entry       = section pair*

section     = lpar word rpar ws
pair        = key equal value ws?

key         = word+
value       = quoted / unquoted
word        = ~r"[-\w\.]+"  # Allows alphanumeric, hyphens, underscores, and periods
quoted      = ~r'"[^"]*"'   # Matches anything inside double quotes
unquoted    = ~r"[^\n]+"    # Matches everything until the end of the line (allows spaces)
equal       = ws? "=" ws?
lpar        = "["
rpar        = "]"
ws          = ~r"\s*"
emptyline   = ws+
"""

EXAMPLE = """
[General]
app_name = MyApp
version = 1.0.0
author = John Doe

[Database]
host = localhost
port = 5432
user = admin
password = secret

[Features]
enable_feature_x = true
enable_feature_y = fa
"""

def main():
	grammar = Grammar(GRAMMAR)
	res = grammar.parse(EXAMPLE)
	print(res)

if __name__ == '__main__':
	main()
```

(this grammar is a modified version of the example from <https://github.com/erikrose/parsimonious#example-usage>)
the example is generated from asking chatgpt for a basic `.ini` file example

**Comment by python357-1** [comment]
I'm sure using a library like that could be better, but a parser (particularly for the very simple "language" we're planning on it being) is not a hard thing to make, and with that particular library, using a parser generator that readily admits it "may be slow and use lots of RAM" and hasn't been actually worked on for over 2 years isn't a great example of why we should use one.

**Comment by Tishj** [comment]
Sure, that's fair.

As far as I know RAM usage depends on the size of the user input and the grammar, which will be small as you said.
I also think that the required complexity of the language will evolve over time, but perhaps this avenue can be revisited when the complexity outgrows the handrolled parser/tokenizer approach

**Comment by python357-1** [comment]
closed in lieu of #606

**Pull request closed without merging**
