### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tadpole256**
In response to an existing issue, I updated the ReadMe to reflect the ability to click "Ctrl-T" to create a new tag. 

I also removed the Warning about having no method to view all tags, as the warning is out of date.

### CODE REVIEW

**Comment by yedpodtrzitko** [comment]
it could be worth it to create standalone section `Hotkeys` with all available hotkeys and shortcuts like this, what do you think?

**Comment by tadpole256** [comment]
I think it could be worth while to have a Hotkeys section, as a quick reference. That would take a bit more time to write.

**Comment by yedpodtrzitko** [comment]
Just start with one. if someone is skimming the readme, they not gonna find it buried in paragraph of text anyway.

**Comment by CyanVoxel** [comment]
Closing this as it hasn't had any activity since the last time feedback was given, and the changes here are subjectively minor.

**Pull request closed without merging**
